version: '3.8'

services:
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    container_name: api-container
    # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual dentro do contêiner para habilitar o live-reload
    volumes:
      - .:/app